// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppDataDir() {
  return window['go']['main']['App']['AppDataDir']();
}

export function AutoSelectBestServer(arg1) {
  return window['go']['main']['App']['AutoSelectBestServer'](arg1);
}

export function Cleanup() {
  return window['go']['main']['App']['Cleanup']();
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function EnsureCore() {
  return window['go']['main']['App']['EnsureCore']();
}

export function FetchSubscription(arg1, arg2) {
  return window['go']['main']['App']['FetchSubscription'](arg1, arg2);
}

export function GetOutboundIP() {
  return window['go']['main']['App']['GetOutboundIP']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SetActiveServer(arg1) {
  return window['go']['main']['App']['SetActiveServer'](arg1);
}

export function SwitchServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['SwitchServer'](arg1, arg2, arg3);
}

export function TestServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestServer'](arg1, arg2, arg3);
}
