// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AppDataDir():Promise<string>;

export function AutoSelectBestServer(arg1:Array<string>):Promise<void>;

export function Cleanup():Promise<void>;

export function Connect(arg1:boolean,arg2:boolean):Promise<string>;

export function Disconnect():Promise<string>;

export function EnsureCore():Promise<void>;

export function FetchSubscription(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetOutboundIP():Promise<string>;

export function GetStats():Promise<domain.Stats>;

export function GetStatus():Promise<Record<string, any>>;

export function SetActiveServer(arg1:number):Promise<void>;

export function SwitchServer(arg1:number,arg2:boolean,arg3:boolean):Promise<string>;

export function TestServer(arg1:string,arg2:number,arg3:string):Promise<domain.PingResult>;
